# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: HUMAN 2022
email: geryxyz@inf.u-szeged.hu
description: >- # this means to ignore newlines until "baseurl:"
  During the HUMAN workshop we seek the possibilities of how human-centric experiments in SE could be shifted from the current state of the practice and enhanced with techniques successfully applied in other scientific areas. In this sense, the workshop will be an interdisciplinary venue. Researchers and practitioners from other fields (e.g., psychology) will be invited to actively participate in the workshop as Keynote speakers and Program Committee members.
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

footer:
  links:
    - label: "SANER"
      icon: "fas fa-chalkboard-teacher"
      url: "https://saner2022.uom.gr/"
    - label: "University of Szeged, Institute of Informatics"
      icon: "fas fa-university"
      url: "https://inf.u-szeged.hu/en"

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: splash
      author_profile: false
      header:
        overlay_color: "#000"
        overlay_filter: "0.5"
        overlay_image: /assets/images/human_banner_4k.jpg
      excerpt: "1st Workshop on Advances in Human-Centric Experiments in Software Engineering"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
